# Site Information
title: design + data
description: A brief resume showcasing education, projects, experience, skills, and interests.
author: Fardeen Bablu
email: fardeenbablu6@gmail.com
url: "https://fbablu.github.io"
baseurl: ""

# Appearance and Metadata
favicon: "logo.png" # Replace with your favicon file
permalink: /:slug.html
remote_theme: riggraz/no-style-please

# Theme Configuration
theme_config:
  appearance: "auto" # Can be "light", "dark", or "auto"
  back_home_text: "<" # Customize text for the homepage link in post layout
  date_format: "%Y-%m-%d" # Customize how the date is formatted
  show_description: false # Show blog description on the homepage

# SASS Configuration
sass:
  style: compressed

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
